### ISSUE TITLE
OG Image now being called twice

### ISSUE THREAD

**Issue by Joomv** [joomla-projects/plg_content_joomlarrssb#10]
https://community.joomla.org/blogs/community/3062-help-to-spread-the-joomla-3-6-love.html
Line 49 and line 54

**Comment by mbabker** [comment]
To be expected.  The [Oepn Graph spec](http://ogp.me/#array) seems to imply you can have multiple tags of some types, unfortunately it doesn't specify which ones that is allowed for.  So I never added a second level check in the template as I did for Twitter's' metadata.

If you know of a source that specifies this better, I'll gladly change behaviors as needed either in the template or here but right now it's a "won't fix" item.
