### ISSUE TITLE
Wrong basepath?

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/plg_content_joomlarrssb#12]
Hi there,
we have an issue on j.org/3 that the /3 is shown twice
`<meta http-equiv="og:url" content="http://repository.joomla.org/3/3/161-the-revolution-in-joomla-ux-improvements">`

Don´t know if there is a misconfiguration or bug. Please help :-)

**Comment by mbabker** [comment]
You'll need to roll back to https://github.com/joomla-projects/plg_content_joomlarrssb/tree/c691fe2b85f6e423219095136b4e7b7a321f5924 or upgrade the `/3` site to 3.6 before I look into this one.  The current master branch is optimized against the 3.6 release and causes invalid metadata to be used.  Granted, the URL thing is probably version independent, but I'd rather not try to debug against a known problematic use case.

**Comment by yvesh** [comment]
@mbabker It's also not working on Joomla 3.6 (latest git)

// Edit: okay looks like you already fixed it :)
