### ISSUE TITLE
Add image width and height to og:tag

### ISSUE THREAD

**Issue by coolcat-creations** [joomla-projects/plg_content_joomlarrssb#14]
"The provided 'og:image' properties are not yet available because new images are processed asynchronously. To ensure shares of new URLs include an image, specify the dimensions using 'og:image:width' and 'og:image:height' tags."

https://developers.facebook.com/docs/sharing/best-practices/#precaching

Can you add this into the plugin? :) THANKS!!!

**Comment by zero-24** [comment]
@coolcat-creations can you please check that this is still an issue and tell me where that infos should be added and are comming from?

**Comment by zero-24** [comment]
Please review this PR: https://github.com/joomla-projects/plg_content_joomlarrssb/pull/23
