### ISSUE TITLE
No more display on category pages - Regression ?

### ISSUE THREAD

**Issue by Sandra97** [joomla-projects/plg_content_joomlarrssb#24]
We used to have the sharing buttons displayed on the category pages. They are not there anymore...

Before: 
![Screenshot_2020-08-31-Joomla-Official-News](https://user-images.githubusercontent.com/4682328/91739953-ebbd9e00-ebb2-11ea-881f-c8b282545a47.jpg)

**Comment by conconnl** [comment]
I have personally never seen them on the page https://www.joomla.org/announcements.html

This site also have some overrides, so I have to check what the problem really is. There were no changes by us on that level.

**Comment by wilsonge** [comment]
Almost certainly the issue michael mentioned here https://github.com/joomla-projects/plg_content_joomlarrssb/pull/20 @HLeithner you broke it basically :P

**Comment by HLeithner** [comment]
I only wrote the pr, I didn't merged it ;-) but at least now we know where to look for the problem

**Comment by conconnl** [comment]
Is this change even needed?
I mean can we just revert it @zero-24 @HLeithner

**Comment by HLeithner** [comment]
It's related to a revert I have done before the release of a 3.9.17

**Comment by zero-24** [comment]
Up to you @HLeithner I can do the revert of your PR here.

**Comment by zero-24** [comment]
Reverted with https://github.com/joomla-projects/plg_content_joomlarrssb/commit/501ad4b347a6dc67e08c5020ba7e67341ba46c77 and released with [3.0.3](https://github.com/joomla-projects/plg_content_joomlarrssb/releases/tag/3.0.3)

Thanks for the report 👍
