### ISSUE TITLE
Use the API :) 

### ISSUE THREAD

**Issue by wilsonge** [joomla-projects/plg_content_joomlarrssb#25]
Instead of using `getimagesize` in the plugin use the wrapper in the Image API (`\Joomla\CMS\Image\Image::getImageFileProperties`)

**Comment by zero-24** [comment]
Fixed by: https://github.com/joomla-projects/plg_content_joomlarrssb/commit/e01d0fa6214015dd4ea36616b98c974c04a9c11b and released with [3.0.3 ](https://github.com/joomla-projects/plg_content_joomlarrssb/releases/tag/3.0.3)
