### ISSUE TITLE
twitter tags

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/plg_content_joomlarrssb#3]
We have the facebook tags - it would be great to have the twitter tags as well - the code to create them is almost identical

http://davidwalsh.name/twitter-cards

**Comment by mbabker** [comment]
Many of these are already part of the base template (see https://github.com/joomla/jdotorgtemplate/blob/master/index.php#L78).  If it doesn't conflict creating multiple tags for the cards, we can add some stuff, or adjust how it's done in the template to allow the content plugin to define things and the template sets defaults if other stuff isn't present.

**Comment by brianteeman** [comment]
Shouldnt the twitter tags be managed exactly the same way as the facebook
tags - i guess thats my point

On 2 September 2015 at 14:41, Michael Babker notifications@github.com
wrote:

> Many of these are already part of the base template (see
> https://github.com/joomla/jdotorgtemplate/blob/master/index.php#L78). If
> it doesn't conflict creating multiple tags for the cards, we can add some
> stuff, or adjust how it's done in the template to allow the content plugin
> to define things and the template sets defaults if other stuff isn't
> present.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/plg_content_joomlarrssb/issues/3#issuecomment-137085728
> .

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
We added the Twitter card metadata before adapting the plugin (and right now .org is the only site using the plugin).  So a bit of re-thinking that whole setup is needed now that we've got this.

**Comment by brianteeman** [comment]
Cool - should be pretty easy now we have the plugin as the twitter data is
almost identical to the facebook data it is already using just with
different tags (at least thats how I did it on my site)

On 2 September 2015 at 14:56, Michael Babker notifications@github.com
wrote:

> We added the Twitter card metadata before adapting the plugin (and right
> now .org is the only site using the plugin). So a bit of re-thinking that
> whole setup is needed now that we've got this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/plg_content_joomlarrssb/issues/3#issuecomment-137090042
> .

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
Ya, I just have to get tricky on figuring out how to parse some of the JDocument data to make sure we can apply our defaults in the template too.  That part's going to be the pain point, unless Twitter's OK with having 2 or 3 of every one of the tags (need to research that too).

**Comment by mbabker** [comment]
Template and plugin updated and pushed to .org.

**Comment by brianteeman** [comment]
thanks

On 3 September 2015 at 14:10, Michael Babker notifications@github.com
wrote:

> Template and plugin updated and pushed to .org.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/plg_content_joomlarrssb/issues/3#issuecomment-137437294
> .

## 

Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
