### ISSUE TITLE
icons in mobile view

### ISSUE THREAD

**Issue by darekmer** [joomla-projects/plg_content_joomlarrssb#39]
Hi, the icons in the mobile view plugin are not fully displayed. Can you fix it?
![mobile](https://user-images.githubusercontent.com/44267306/229448612-d847efa0-ea5b-4d75-bee0-d8741ac15f19.png)

**Comment by darekmer** [comment]
Can you fix it? Please.

**Comment by darekmer** [comment]
Can you fix it? Please.

**Comment by stutteringp0et** [comment]
Add this to your css and it's fixed:

`
.rrssb-buttons li.small a span.rrssb-icon {
    overflow: visible;
}
`
