### ISSUE TITLE
Email sharing doesn't seem to be behaving correctly

### ISSUE THREAD

**Issue by Joomv** [joomla-projects/plg_content_joomlarrssb#8]
When you click on the email share button and are using Outlook, you get the Title with + instead of spaces and a body call that stays in the subject line.

Changing line 25 of /plugins/content/joomlarrssb/tmpl/default.php
from 
`<a href="mailto:?subject=<?php echo urlencode($article->title); ?>body=<?php echo urlencode($itemURL); ?>">
`
to
`<a href="mailto:?subject=<?php echo ($article->title); ?>&amp;body=<?php echo urlencode($itemURL); ?>">`

Appears to fix this.

**Comment by mbabker** [comment]
As long as the browsers all work OK without the subject URL encoded it's a good fix.  I just don't want to break the browsers for the sake of good pre-filled subject lines in the email clients.

**Comment by Joomv** [comment]
I'll try and do some further testing.  Even if the subject line is left as urlencoded, we need the &amp; before the body call.

**Comment by mbabker** [comment]
Ampersand's added in now.
